[batch] Fix broken batch worker image pulling
I thought that pulling with no auth would use the credential helper to use the machine's
credentials. AFAICT, the Docker HTTP API has no way to use the credential helper. You *must* provide
authentication in the HTTP request which means the HTTP client must obtain the credentials
themselves. The Docker docs note ["Authentication for registries is handled client side. The client
has to send authentication details to various endpoints that need to communicate with
registries"](https://docs.docker.com/engine/api/v1.41/#section/Authentication)

I request a short-lived oauth2 access token from the Google metadata endpoint. The google
[documentation obliquely notes that the username should be
`oauth2accesstoken`](https://cloud.google.com/container-registry/docs/advanced-authentication). I
use this only for retrieving a "public gcr image" which I fix in this PR to be images whose
"repository" [1] is one of these:
- gcr.io/PROJECT/query
- gcr.io/PROJECT/hail
- gcr.io/PROJECT/python-dill

A previous Shuffler PR taught worker.py to translate our `hailgenetics` Docker image names to
`gcr.io/PROJECT` image names.

From a relevant Docker worker log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/batch/worker/worker.py", line 359, in ensure_image_is_pulled
    docker.images.get, self.image)
  File "/usr/local/lib/python3.7/site-packages/batch/worker/worker.py", line 111, in wrapper
    return await asyncio.wait_for(f(*args, **kwargs), timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.7/site-packages/aiodocker/images.py", line 46, in get
    return await self.inspect(name)
  File "/usr/local/lib/python3.7/site-packages/aiodocker/images.py", line 36, in inspect
    response = await self.docker._query_json("images/{name}/json".format(name=name))
  File "/usr/local/lib/python3.7/site-packages/aiodocker/docker.py", line 223, in _query_json
    path, method, params=params, data=data, headers=headers, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/aiodocker/docker.py", line 291, in __aenter__
    resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiodocker/docker.py", line 206, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
aiodocker.exceptions.DockerError: DockerError(404, 'no such image: gcr.io/hail-vdc/query:tfkm2kev7zcf: No such image: gcr.io/hail-vdc/query:tfkm2kev7zcf')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/batch/worker/worker.py", line 372, in run
    await self.ensure_image_is_pulled()
  File "/usr/local/lib/python3.7/site-packages/batch/worker/worker.py", line 363, in ensure_image_is_pulled
    docker.images.pull, self.image)
  File "/usr/local/lib/python3.7/site-packages/batch/worker/worker.py", line 111, in wrapper
    return await asyncio.wait_for(f(*args, **kwargs), timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.7/site-packages/aiodocker/images.py", line 104, in _handle_list
    async with cm as response:
  File "/usr/local/lib/python3.7/site-packages/aiodocker/docker.py", line 291, in __aenter__
    resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiodocker/docker.py", line 206, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
aiodocker.exceptions.DockerError: DockerError(500, "unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")
```

[1] The Docker specifications are confusing. After reading
[v1](https://github.com/moby/moby/blob/master/image/spec/v1.md) and
[v1.2](https://github.com/moby/moby/blob/master/image/spec/v1.2.md), it seems that the "repository"
is everything before the last colon and the "image name suffix" is everything after the last
colon. For example, in `server:8080/abc/def:123`, the repository is `server:8080/abc/def` and the
"image name suffix" is `123`.