[benchmarks] Fix benchmark combine after scipy update (#10062)
`scipy.stats.f_oneway` now throws if only one arg is passed:

```
TypeError: at least two inputs are required; got 1.
```