[batch] Improve inactive client UX (#15298)
## Change Description

Wires through the not authenticated message for hailtop.batch users who
are unauthenticated or inactive.

Before: See [#Hail Batch support > Hail Batch issue with submission @
💬](https://hail.zulipchat.com/#narrow/channel/223457-Hail-Batch-support/topic/Hail.20Batch.20issue.20with.20submission/near/575340129)

After: 
```
Traceback (most recent call last):
  File ".../hello.py", line 3, in <module>
    b = hb.Batch('hello test')
        ^^^^^^^^^^^^^^^^^^^^^^
  File ".../hail/python/hailtop/batch/batch.py", line 197, in __init__
    self._backend = ServiceBackend()
                    ^^^^^^^^^^^^^^^^
  File ".../hail/python/hailtop/batch/backend.py", line 645, in __init__
    regions = [ServiceBackend.default_region()]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../hail/python/hailtop/batch/backend.py", line 569, in default_region
    raise e.with_traceback(None) from None
hailtop.batch_client.aioclient.BatchNotAuthenticatedError: Not authenticated with Hail Batch.

Please run:

    hailctl auth login

to obtain credentials. If problems persist, try logging in to the web UI to check account status.
```

Note: It would probably be even better to return the `inactive` state
directly via the APIs, so we don't have to say "or try logging in to the
web UI", but that's probably a much bigger change

## Security Assessment

Delete all except the correct answer:
- This change potentially impacts the Hail Batch instance as deployed by
Broad Institute in GCP

### Impact Rating
- This change has a low security impact


### Impact Description

Better catching of inactive errors in the client

### Appsec Review

- [ ] Required: The impact has been assessed and approved by appsec