[batch] Migrate editable install packages to uv_build (#15048)
## Change Description

Fixes #15009

At some point, following the steps to spin up the dev server began to
fail with an error like
```
  File "/Users/kchandra/workspace/hail/devbin/dev_proxy.py", line 8, in <module>
    from web_common import render_template, setup_aiohttp_jinja2, setup_common_static_routes
ImportError: cannot import name 'render_template' from 'web_common' (unknown location)
```

As far as I can tell, the context for what happened is something like
this:

- There is a long-standing effort to standardize Python builds and
installs - see [PEP517](https://peps.python.org/pep-0517/) and
[PEP660](https://peps.python.org/pep-0660/), which define a new standard
for editable installs.
- As part of this, the legacy mechanism used by `setuptools` for
editable installs will be deprecated in favor of the new standardized
solution: https://github.com/pypa/pip/issues/11457
- Recent `setuptools` updates have begun to migrate users off of the
legacy mechanism (ex. https://github.com/pypa/setuptools/pull/4955). In
theory, if our packages use `src` layout & have moved from `setup.py` to
`pyproject.toml`, this should have had no effect. Unfortunately, neither
of these conditions are true.
- Presumably because of resulting changes in behavior, we're now hitting
a [edge
case](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#id2)
in `setuptools` where the dev proxy imports a local folder in the
current directory instead of the installed package with the same name.

[`uv_build`](https://docs.astral.sh/uv/concepts/build-backend/) supports
the new install mechanisms and we're using `uv` elsewhere already, so
this seemed like a good alternative to `setuptools` with the same
advantages as `uv`.

- `batch make devserver` works both when the packages are installed
normally and when they use an editable install.
- Verified the remote server still works after a `dev deploy`.


## Security Assessment

- This change potentially impacts the Hail Batch instance as deployed by
Broad Institute in GCP

### Impact Rating

- This change has no security impact

### Impact Description

This changes the build system for these three packages, but the build
artifacts should be the same as before.

### Appsec Review

- [ ] Required: The impact has been assessed and approved by appsec

---------

Co-authored-by: Patrick Schultz <pschultz@broadinstitute.org>
Co-authored-by: Chris Llanwarne <cjllanwarne@users.noreply.github.com>
Co-authored-by: Christopher Vittal <cvittal@broadinstitute.org>