[batch|ui] Improved inactivity error messages (#15620)
## Change Description

Users are meant to receive an informative error message if they attempt
to use Hail while their account has been marked as inactive. Currently,
the intended error message does not make its way to users for a variety
of reasons (for example, users are attempting to use Hail in a session
id-based setting like a Jupyter notebook, or the error message is
swallowed by other auth checks we make along the way).

This PR adds explicit inactive user checks for i) login id and hail
identity id and ii) session id, whereby we're now able to handle and
raise appropriate errors if a user is inactive.

### Testing
Error message successfully propagated in the CLI after attempting to
submit a job while inactive:
```bash
ClientResponseError: 403, message='Forbidden', url=URL('https://internal.hail.is/grohlice/auth/api/v1alpha/userinfo') body='Your Hail account is inactive. Please contact a Hail 
administrator to reactivate.'
```
Error message presented to inactive users attempting to log in via the
web UI:
<img width="653" height="232" alt="image"
src="https://github.com/user-attachments/assets/6e132b4b-90d4-495b-bae3-d96b423d1e7b"
/>


## Security Assessment
- This change potentially impacts the Hail Batch instance as deployed by
Broad Institute in GCP

### Impact Rating
- This change has a low security impact

### Impact Description
This PR adds new auth checks specific to inactive users. However,
nothing has been removed from our already existing checks (relating to
`get_userinfo()`), and users should still be subject to the same
authentication scrutiny as before.

### Appsec Review

- [ ] Required: The impact has been assessed and approved by appsec