[query] Make pyToDF use long lived temp files (again) (#14907)
It is possible that the partition function can outlive the
ExecuteContext in TableValue.toDF. Therefore, any temporary files needed
for future stages must still be around, so we need to set
selfContainedExecution to false for pyToDF.

Fixes [#Hail Query 0.2 support > MT to parquet throwing
FileNotFoundException: Item not found @
💬](https://hail.zulipchat.com/#narrow/channel/123010-Hail-Query-0.2E2-support/topic/MT.20to.20parquet.20throwing.20FileNotFoundException.3A.20Item.20not.20found/near/522209026)
reported by @ch-kr on Zulip.

## Security Assessment
- This change cannot impact the Hail Batch instance as deployed by Broad
Institute in GCP