[query] update scala version (#12951)
Summary:
The correct default scala version for Spark 3.3.0 is 2.12.15
The main change is in `hail/build.gradle` the remaining is just for
consistency.

References:
https://github.com/apache/spark/blob/v3.3.0/pom.xml#L3527 (show scala
version pinned by Spark)
https://github.com/hail-is/hail/blob/0.2.115/hail/build.gradle#L45-L50

This mismatch causing an issue in our environment when opening
spark-shell because hail-all-spark.jar is bundled with scala-reflect
that has missing classes. The ideal solution is to remove scala language
packages as part of the shadow jar because these already come with the
Spark distribution, but proposing to have them in-sync as a workaround
for now.

```
$ spark-shell
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
...
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.reflect.internal.settings.MutableSettings scala.reflect.internal.settings.MutableSettings$.SettingsOps(scala.reflect.internal.settings.MutableSettings)'
        at scala.tools.nsc.interpreter.ILoop.$anonfun$chooseReader$1(ILoop.scala:914)
        at scala.tools.nsc.interpreter.ILoop.mkReader$1(ILoop.scala:920)
        at scala.tools.nsc.interpreter.ILoop.$anonfun$chooseReader$4(ILoop.scala:926)
        at scala.tools.nsc.interpreter.ILoop.$anonfun$chooseReader$3(ILoop.scala:926)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:926)
        at org.apache.spark.repl.SparkILoop.$anonfun$process$1(SparkILoop.scala:138)
...
```

The error is caused by the change in between 2.12.13 and 2.12.15 in the
scala-reflect package that has an additional implicit class:

https://github.com/scala/scala/blob/v2.12.13/src/reflect/scala/reflect/internal/settings/MutableSettings.scala

https://github.com/scala/scala/blob/v2.12.15/src/reflect/scala/reflect/internal/settings/MutableSettings.scala#L88

See also this thread in zulipchat that I posted a while back:

https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/scala.20class.20files.20bundled.20in.20hail-all-spark.2Ejar